In [2]:
import pandas as pd 
myfile=pd.read_csv('student.csv')  #will load the csv file 
print(myfile.to_string)

<bound method DataFrame.to_string of     student_id  age  gender  study_hours_per_day  social_media_hours  \
0        S1000   23  Female                  0.0                 1.2
1        S1001   20  Female                  6.9                 2.8
2        S1002   21    Male                  1.4                 3.1
3        S1003   23  Female                  1.0                 3.9
4        S1004   19  Female                  5.0                 4.4
..         ...  ...     ...                  ...                 ...
995      S1995   21  Female                  2.6                 0.5
996      S1996   17  Female                  2.9                 1.0
997      S1997   20    Male                  3.0                 2.6
998      S1998   24    Male                  5.4                 4.1
999      S1999   19  Female                  4.3                 2.9

     netflix_hours part_time_job  attendance_percentage  sleep_hours  \
0              1.1            No                   85.0          8.0
1              2.3            No                   97.3          4.6
2              1.3            No                   94.8          8.0
3              1.0            No                   71.0          9.2
4              0.5            No                   90.9          4.9
..             ...           ...                    ...          ...
995            1.6            No                   77.0          7.5
996            2.4           Yes                   86.0          6.8
997            1.3            No                   61.9          6.5
998            1.1           Yes                  100.0          7.6
999            1.9            No                   89.4          7.1

    diet_quality  exercise_frequency parental_education_level  \
0           Fair                   6                   Master
1           Good                   6              High School
2           Poor                   1              High School
3           Poor                   4                   Master
4           Fair                   3                   Master
..           ...                 ...                      ...
995         Fair                   2              High School
996         Poor                   1              High School
997         Good                   5                 Bachelor
998         Fair                   0                 Bachelor
999         Good                   2                 Bachelor

    internet_quality  mental_health_rating extracurricular_participation  \
0            Average                     8                           Yes
1            Average                     8                            No
2               Poor                     1                            No
3               Good                     1                           Yes
4               Good                     1                            No
..               ...                   ...                           ...
995             Good                     6                           Yes
996          Average                     6                           Yes
997             Good                     9                           Yes
998          Average                     1                            No
999          Average                     8                            No

     exam_score
0          56.2
1         100.0
2          34.3
3          26.8
4          66.4
..          ...
995        76.1
996        65.9
997        64.4
998        69.7
999        74.9

[1000 rows x 16 columns]>

In [ ]:
print(len(myfile)) #total number of students

1000

In [43]:
newfile3=myfile[myfile["study_hours_per_day"]>2] #no of students with study hours more than 2 
num3=len(newfile3)
print(num3)

846

In [15]:
myfile[myfile["exam_score"]>40]

,student_id,age,gender,study_hours_per_day,social_media_hours,netflix_hours,part_time_job,attendance_percentage,sleep_hours,diet_quality,exercise_frequency,parental_education_level,internet_quality,mental_health_rating,extracurricular_participation,exam_score
0,S1000,23,Female,0.0,1.2,1.1,No,85.0,8.0,Fair,6,Master,Average,8,Yes,56.2
1,S1001,20,Female,6.9,2.8,2.3,No,97.3,4.6,Good,6,High School,Average,8,No,100.0
4,S1004,19,Female,5.0,4.4,0.5,No,90.9,4.9,Fair,3,Master,Good,1,No,66.4
5,S1005,24,Male,7.2,1.3,0.0,No,82.9,7.4,Fair,1,Master,Average,4,No,100.0
6,S1006,21,Female,5.6,1.5,1.4,Yes,85.8,6.5,Good,2,Master,Poor,4,No,89.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,S1995,21,Female,2.6,0.5,1.6,No,77.0,7.5,Fair,2,High School,Good,6,Yes,76.1
996,S1996,17,Female,2.9,1.0,2.4,Yes,86.0,6.8,Poor,1,High School,Average,6,Yes,65.9
997,S1997,20,Male,3.0,2.6,1.3,No,61.9,6.5,Good,5,Bachelor,Good,9,Yes,64.4
998,S1998,24,Male,5.4,4.1,1.1,Yes,100.0,7.6,Fair,0,Bachelor,Average,1,No,69.7
999,S1999,19,Female,4.3,2.9,1.9,No,89.4,7.1,Good,2,Bachelor,Average,8,No,74.9

In [40]:
newfile=myfile[(myfile["study_hours_per_day"]>2) & (myfile["exam_score"]>40)]
num1=len(newfile)
print(num1/1000*100)   #percentage of students with study hours more than 2 and passed exam

84.2

In [46]:
#bayes theorem to find probability that student studied more than 2 hours given the student passed 
#P(studied>2hours|passed)=[P(passed|studied>2hours) X P(studied)]/[P(passed)]
#P(passed)=[P(passed|studied>2hours) X P(studied) + P(passed/didntstudy) X P(didntstudy)]
#this is the formula 
#now, I did math in notebook and found the inputs by len/1000 of every condition and I got:
#P(passed)=0.7251
#P(studied>2hours)=0.846
#P(didnt study)=0.133
#P(passed/didntstudy)=0.096
#P(passed|studied)=0.842
#therefore, using baye's P(studied>2hours|passed) = 0.98239
#I could have compiled everything and found by code but it would be too tedius 
print(0.98239)

0.98239